CREATE TABLE IF NOT EXISTS `pixl_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(80) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` DATETIME NULL,
  `site_id` VARCHAR(100) NOT NULL DEFAULT '',
  `reason` VARCHAR(40) NOT NULL DEFAULT '',
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `hostname` VARCHAR(255) NOT NULL DEFAULT '',
  `page_url` TEXT NULL,
  `path` VARCHAR(1024) NOT NULL DEFAULT '',
  `referrer` TEXT NULL,
  `browser` VARCHAR(80) NOT NULL DEFAULT '',
  `os` VARCHAR(80) NOT NULL DEFAULT '',
  `device` VARCHAR(80) NOT NULL DEFAULT '',
  `country` VARCHAR(20) NOT NULL DEFAULT '',
  `language` VARCHAR(40) NOT NULL DEFAULT '',
  `screen` VARCHAR(40) NOT NULL DEFAULT '',
  `viewport` VARCHAR(40) NOT NULL DEFAULT '',
  `screen_category` VARCHAR(40) NOT NULL DEFAULT '',
  `known_resolution` TINYINT(1) NOT NULL DEFAULT 0,
  `session_duration` INT UNSIGNED NULL,
  `reading_label` VARCHAR(40) NOT NULL DEFAULT '',
  `reading_seconds` INT UNSIGNED NULL,
  `reading_score` INT UNSIGNED NULL,
  `v3_user_score` DECIMAL(10,2) NULL,
  `render_status` VARCHAR(255) NOT NULL DEFAULT '',
  `console_error_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `dialog_error_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `source` VARCHAR(40) NOT NULL DEFAULT '',
  `is_bot` TINYINT(1) NOT NULL DEFAULT 0,
  `bot_score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `bot_category` VARCHAR(80) NOT NULL DEFAULT '',
  `bot_name` VARCHAR(120) NOT NULL DEFAULT '',
  `bot_reasons` TEXT NULL,
  `visitor_hash` CHAR(64) NOT NULL DEFAULT '',
  `ip_hash` CHAR(64) NOT NULL DEFAULT '',
  `request_method` VARCHAR(12) NOT NULL DEFAULT '',
  `request_uri` TEXT NULL,
  `user_agent` TEXT NULL,
  `message` TEXT NULL,
  `payload_json` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `event_id` (`event_id`),
  KEY `created_at` (`created_at`),
  KEY `site_reason_created` (`site_id`, `reason`, `created_at`),
  KEY `host_path_created` (`hostname`, `path`(191), `created_at`),
  KEY `device_created` (`device`, `browser`, `os`, `created_at`),
  KEY `country_created` (`country`, `created_at`),
  KEY `bot_created` (`is_bot`, `bot_category`, `created_at`),
  KEY `visitor_created` (`visitor_hash`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
