'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
let checks = 0;
const check = (condition, label) => { assert.ok(condition, label); checks++; };
(async () => {
  const base = process.env.EXPORT_TEST_BASE_URL;
  assert.match(base || '', /^http:\/\/127\.0\.0\.1:\d+$/);
  const at = Number(process.env.EXPORT_TEST_NOW);
  const directory = process.env.TEST_ARTIFACT_DIR || fs.mkdtempSync(path.join(os.tmpdir(), 'stats3-export-browser-'));
  fs.mkdirSync(directory, { recursive: true });
  const browser = await chromium.launch({ headless:true, executablePath:process.env.BROWSER_EXECUTABLE || '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge' });
  try {
    const context = await browser.newContext({ viewport:{ width:1440, height:900 }, acceptDownloads:true, colorScheme:'light' });
    const [name, value] = process.env.EXPORT_TEST_COOKIE.split('=');
    await context.addCookies([{ name, value, url:base }]);
    await context.route('**/*', route => route.request().url().startsWith(base) ? route.continue() : route.abort());
    const page = await context.newPage();
    await page.goto(base + '/stats.php?range=60min&exclude_germans=1');
    const link = page.getByRole('link', { name:'Export', exact:true });
    check(await link.getAttribute('href') === 'export.php' && await link.getAttribute('download') === null, 'dashboard Export opens new page');
    await link.click();
    await page.waitForURL(base + '/export.php');
    check(await page.getByRole('heading', { name:'Export & Daten-Backup', exact:true }).isVisible(), 'real navigation opens export overview');
    await page.goto(base + '/export.php?at=' + at);
    await page.waitForFunction(() => document.documentElement.dataset.archiveReady === 'true');
    const runtimeRequests = [];
    page.on('request',request=>runtimeRequests.push(request.url()));
    check(await page.locator('#sourceTable tbody tr').count() === 15, 'all 15 sources listed');
    check(await page.locator('.source-card').count() === 15, 'each statistics area has metrics and details');
    check(await page.getByText('49', { exact:true }).first().isVisible(), 'complete event count is shown');
    const downloadFile = async (selector, filename) => {
      const pending = page.waitForEvent('download');
      await page.locator(selector).click();
      const download = await pending;
      check(await download.failure() === null, filename + ' downloads completely');
      const output = path.join(directory, filename);
      await download.saveAs(output);
      return { content:fs.readFileSync(output,'utf8'), filename:download.suggestedFilename() };
    };
    const csv = await downloadFile('#csvDownload', 'export.csv');
    check(csv.filename === 'export.csv' && csv.content.startsWith('\uFEFFStatistik;Tabelle;'), 'CSV keeps existing filename and header');
    for (const marker of ['export-current-bot','München','export-stat4-event','ppcmate_conversions','pixl_captcha_stats','Historische Statistikdaten']) check(csv.content.includes(marker), 'CSV includes ' + marker);
    check(!csv.content.includes('DO_NOT_EXPORT_') && !csv.content.includes('excluded-'), 'CSV respects scope and excluded secrets');
    const json = await downloadFile('#backupDownload', 'backup.json');
    const backup = JSON.parse(json.content);
    check(/^stats3-backup-\d{8}-\d{6}\.json$/.test(json.filename), 'JSON filename includes timestamp');
    check(backup.meta.summary.total_rows === 63 && backup.tables.length === 15, 'JSON has complete matching fixture data');
    check(backup.meta.summary.window.to_unix - backup.meta.summary.window.from_unix === 90*86400, 'JSON time window is capped');
    check(page.url() === base + '/export.php?at=' + at, 'downloads leave the overview open');
    await page.locator('#sourceSearch').fill('Mind');
    check(await page.locator('#sourceTable tbody tr:visible').count() === 2 && await page.locator('.source-card:visible').count() === 2, 'source search filters table and metric cards');
    await page.locator('#sourceSearch').fill('not-a-source');
    check(await page.locator('#noSources').isVisible(), 'source search empty state');
    await page.locator('#sourceSearch').fill('');
    await page.screenshot({ path:path.join(directory,'export-desktop.png'), fullPage:true });
    await page.locator('#sourceTable tbody tr').first().getByRole('link').click();
    check(await page.locator('.record').count() === 20 && page.url().endsWith('#datensaetze'), 'all embedded raw records are locally paginated and scrolled into view');
    await page.locator('.record').first().locator('summary').click();
    check(await page.locator('.record').first().locator('pre').filter({hasText:'München'}).count() > 0, 'complete Unicode record can be expanded');
    await page.locator('.record').nth(2).locator('summary').click();
    check(await page.locator('.record').nth(2).innerText().then(t => t.includes('<img src=x')), 'stored HTML appears literally');
    check(await page.evaluate(() => !window.exportXss) && await page.locator('.record img').count() === 0, 'record values cannot run stored script');
    for (const width of [320,375,390,430,720,844,1024,1440]) {
      await page.setViewportSize({width,height:900});
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no page overflow at ' + width);
    }
    await page.setViewportSize({width:390,height:844});
    await page.locator('#datensaetze').screenshot({path:path.join(directory,'export-mobile-records.png')});
    await page.getByRole('button',{name:'Weiter',exact:true}).click();
    await page.getByRole('button',{name:'Weiter',exact:true}).click();
    check(await page.locator('.record').count() === 9 && await page.locator('.pagination').innerText().then(t=>t.includes('Seite 3 von 3')), 'last page retains all remaining records');
    check(await page.getByRole('button',{name:'Weiter',exact:true}).isDisabled(), 'last page has no enabled next button');
    await page.getByRole('button',{name:'Zurück',exact:true}).click();
    check(await page.locator('.record').count() === 20, 'previous page works');
    const filterExpected = {'60min':30,'24h':33,'7d':36,'14d':39,'1m':42,'2m':45,'3m':49};
    const chooseRange = async (target,range) => {
      await target.locator('[data-range="'+range+'"]').click();
      await target.waitForFunction(range=>document.documentElement.dataset.initialRange === range && !document.getElementById('filterStatus').hasAttribute('aria-busy'),range);
    };
    for (const [range,count] of Object.entries(filterExpected)) {
      await chooseRange(page,range);
      check(await page.locator('#sourceTable tbody tr').first().locator('.selected-count').textContent() === String(count), 'online static filter '+range+' uses all matching records');
      check(await page.locator('#pageLabel').innerText().then(text=>text.startsWith('Seite 1 ')), 'filter resets detail page for '+range);
    }
    check(runtimeRequests.length === 0, 'filters, pages, search and downloads make zero HTTP requests');
    await chooseRange(page,'60min');
    const html = await downloadFile('#htmlDownload','backup.html');
    check(/^stats3-backup-\d{8}-\d{6}\.html$/.test(html.filename), 'HTML filename includes saved timestamp');
    check(html.content.includes('data-offline="true"') && html.content.includes('data-initial-range="60min"'), 'HTML keeps the selected view');
    check(html.content.includes('page-44') && html.content.includes('boundary-start'), 'filtered HTML still includes the entire 90-day dataset');
    check(!/<(?:script|link)[^>]+(?:src|href)=/i.test(html.content), 'downloaded HTML has no external scripts or styles');
    const offline = await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:900},offline:true});
    await offline.addInitScript(() => { Date.now = () => Date.UTC(2040,0,1); });
    const filePage = await offline.newPage();
    const fileRequests = [], scriptErrors = [];
    filePage.on('request',request=>{ if (/^https?:/.test(request.url())) fileRequests.push(request.url()); });
    filePage.on('pageerror',error=>scriptErrors.push(error.message));
    await filePage.goto(pathToFileURL(path.join(directory,'backup.html')).href);
    await filePage.waitForFunction(() => document.documentElement.dataset.archiveReady === 'true' && document.querySelectorAll('[data-range]')[0].disabled === false);
    check(await filePage.locator('#sourceTable tbody tr').first().locator('.selected-count').textContent() === '30', 'saved 60-minute view works offline in a later year');
    check(await filePage.locator('.server-link:visible').count() === 0, 'offline archive has no server navigation');
    for (const [range,count] of Object.entries(filterExpected)) {
      await chooseRange(filePage,range);
      check(await filePage.locator('#sourceTable tbody tr').first().locator('.selected-count').textContent() === String(count), 'offline filter '+range+' recomputes counts');
    }
    await filePage.locator('#sourceTable tbody tr').first().getByRole('link').click();
    await filePage.getByRole('button',{name:'Weiter',exact:true}).click();
    await filePage.getByRole('button',{name:'Weiter',exact:true}).click();
    check(await filePage.locator('.record').count() === 9 && await filePage.locator('.record').last().innerText().then(text=>text.includes('Datensatz 49')), 'last embedded record is accessible offline');
    await chooseRange(filePage,'60min');
    const offlineJsonPromise = filePage.waitForEvent('download');
    await filePage.locator('#backupDownload').click();
    const offlineJson = await offlineJsonPromise;
    const offlineJsonPath = path.join(directory,'offline-backup.json');
    await offlineJson.saveAs(offlineJsonPath);
    check(JSON.parse(fs.readFileSync(offlineJsonPath,'utf8')).meta.summary.total_rows === 63, 'offline JSON download retains all rows after a shorter filter');
    const offlineCsvPromise = filePage.waitForEvent('download');
    await filePage.locator('#csvDownload').click();
    const offlineCsv = await offlineCsvPromise;
    const offlineCsvPath = path.join(directory,'offline-export.csv');
    await offlineCsv.saveAs(offlineCsvPath);
    check(fs.readFileSync(offlineCsvPath,'utf8') === csv.content, 'offline CSV matches full original CSV');
    for (const width of [320,375,390,430,720,844,1024,1440]) {
      await filePage.setViewportSize({width,height:900});
      check(await filePage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'offline filters fit width '+width);
    }
    await filePage.setViewportSize({width:390,height:844});
    await filePage.locator('#themeToggle').click();
    await filePage.evaluate(()=>window.scrollTo(0,0));
    await filePage.screenshot({path:path.join(directory,'static-export-mobile.png')});
    check(fileRequests.length === 0 && scriptErrors.length === 0, 'offline HTML makes no HTTP requests and has no script errors');
    await offline.close();
    await page.goto(base + '/export.php?at=' + at);
    await page.locator('#themeToggle').click();
    check(await page.locator('html').getAttribute('data-theme') === 'dark', 'dark mode works');
    await page.reload();
    check(await page.locator('html').getAttribute('data-theme') === 'dark', 'dark mode persists');
    await page.screenshot({path:path.join(directory,'export-mobile.png'),fullPage:true});
    const noJs = await browser.newContext({javaScriptEnabled:false});
    await noJs.addCookies([{name,value,url:base}]);
    const noJsPage = await noJs.newPage();
    await noJsPage.goto(base + '/export.php?at=' + at);
    check(await noJsPage.locator('#sourceTable tbody tr').count() === 15 && await noJsPage.locator('#backupDownload').isVisible(), 'overview and backup also work without JavaScript');
    await noJs.close();
    await context.clearCookies();
    await page.goto(base + '/export.php?download=json');
    check(await page.locator('input[name=stats_password]').isVisible() && await page.locator('#sourceTable').count() === 0, 'expired login shows no data');
    await page.locator('input[name=stats_password]').fill('export-fixture-password');
    await page.getByRole('button',{name:'Einloggen'}).click();
    await page.waitForURL(base + '/export.php');
    check(await page.locator('#backupDownload').isVisible(), 'login returns to export overview');
    console.log(`PASS export browser: ${checks} checks; standalone HTML, seven offline filters, complete data, CSV/JSON, no network, pagination, 8 widths, XSS, no-JS and login`);
    console.log('Export preview artifacts: ' + directory);
  } finally { await browser.close(); }
})().catch(error=>{ console.error(error); process.exitCode=1; });
